# Generated by Django 2.2 on 2020-02-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadowhandsession',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
