# Generated by Django 2.2 on 2020-02-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_shadowhandsession_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shadowhandsession',
            name='recruit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruit.Recruit'),
        ),
    ]
