# Generated by Django 2.2 on 2020-02-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planet',
            options={'ordering': ['name'], 'verbose_name': 'Планету', 'verbose_name_plural': 'Планеты'},
        ),
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование'),
        ),
    ]
