# Generated by Django 2.2 on 2020-02-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruit', '0001_initial'),
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Planet', verbose_name='Планета')),
            ],
            options={
                'verbose_name': 'Ситха',
                'verbose_name_plural': 'Ситхи',
            },
        ),
        migrations.CreateModel(
            name='ShadowHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Recruit')),
                ('sith_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sith.Sith')),
            ],
        ),
    ]
