# Generated by Django 2.2 on 2020-02-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sith', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shadowhand',
            name='recruit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruit.Recruit'),
        ),
        migrations.AlterField(
            model_name='sith',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
    ]
